## Software installation
- include_tasks: "install-{{ ansible_distribution|lower }}.yml"

## Configuration
- include_tasks: configure.yml

## Storage pools
- include_tasks: storage-pool.yml
  loop_control:
    loop_var: pool
  loop: "{{ linstor_pools }}"
  when:
  - "'linstor_satellites' in group_names"
